#use_frameworks!

platform :ios, '8.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'CocoaLumberjack' || target.name == 'CocoaHTTPServer'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) DD_LEGACY_MACROS=1'
      end
      
#      if target.name == 'SJVideoPlayer' || target.name == 'SJBaseVideoPlayer'
#        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
#      end
    end
  end
end

target 'SJM3U8Downloader_Example' do
  
  pod 'SJM3U8Downloader', :path => '../'
  pod 'SJUIKit/Base'
  pod 'SJUIKit/AttributesFactory'
  
  target 'SJM3U8Downloader_Tests' do
    inherit! :search_paths
  end
end
