use_frameworks!

platform :ios, '8.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DD_LEGACY_MACROS=1']
    end
  end
end

target 'SJM3U8Downloader_Example' do
  
  pod 'SJM3U8Downloader', :path => '../'
  pod 'YYModel'
  pod 'SJUIKit'
  
  target 'SJM3U8Downloader_Tests' do
    inherit! :search_paths
  end
end
