# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SJM3U8DownloadProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SJM3U8DownloadProject
 
  pod 'CocoaHTTPServer' 



  target 'SJM3U8DownloadProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SJM3U8DownloadProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
